import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// components
import Navbar from "@/components/layouts/navbar";
import SideNavbar from "@/components/layouts/sideNavbar";
import Footer from "@/components/layouts/footer";
import MainContent from "@/components/layouts/mainContent";
// context
import { SidebarProvider } from "@/lib/sidebarContext";
// styles
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <SidebarProvider>
          <SideNavbar />
          <MainContent>
            <main className="my-20">{children}</main>
            <Footer />
          </MainContent>
        </SidebarProvider>
      </body>
    </html>
  );
}
